In [9]:
pip install numpy pandas seaborn matplotlib statsmodels

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.13/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
a=pd.read_csv("/content/daily_dataset.csv")

In [14]:
a

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000131,2011-12-15,0.4850,0.432045,0.868,22.0,0.239146,9.505,0.072
1,MAC000131,2011-12-16,0.1415,0.296167,1.116,48.0,0.281471,14.216,0.031
2,MAC000131,2011-12-17,0.1015,0.189812,0.685,48.0,0.188405,9.111,0.064
3,MAC000131,2011-12-18,0.1140,0.218979,0.676,48.0,0.202919,10.511,0.065
4,MAC000131,2011-12-19,0.1910,0.325979,0.788,48.0,0.259205,15.647,0.066
...,...,...,...,...,...,...,...,...,...
292546,MAC000854,2012-10-20,0.1440,0.172563,1.468,48.0,0.217906,8.283,0.015
292547,MAC000854,2012-10-21,0.1675,0.159646,0.509,48.0,0.104313,7.663,0.022
292548,MAC000854,2012-10-22,0.1530,0.143771,0.495,48.0,0.102161,6.901,0.015
292549,MAC000854,2012-10-23,0.1465,0.145729,0.439,48.0,0.103772,6.995,0.026
292550,MAC000854,2012-10-24,0.1295,0.153042,NaN,NaN,NaN,NaN,NaN

In [15]:
a["energy_count"]=pd.to_datetime(a["energy_count"])
a["energy_count"]

0        1970-01-01 00:00:00.000000022
1        1970-01-01 00:00:00.000000048
2        1970-01-01 00:00:00.000000048
3        1970-01-01 00:00:00.000000048
4        1970-01-01 00:00:00.000000048
                      ...
292546   1970-01-01 00:00:00.000000048
292547   1970-01-01 00:00:00.000000048
292548   1970-01-01 00:00:00.000000048
292549   1970-01-01 00:00:00.000000048
292550                             NaT
Name: energy_count, Length: 292551, dtype: datetime64[ns]

In [16]:
a=a.sort_values("energy_count")
a

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
205939,MAC001065,2012-12-18,NaN,NaN,NaN,1970-01-01 00:00:00.000000000,NaN,NaN,NaN
129012,MAC005560,2012-12-19,NaN,NaN,NaN,1970-01-01 00:00:00.000000000,NaN,NaN,NaN
138461,MAC002110,2012-12-18,NaN,NaN,NaN,1970-01-01 00:00:00.000000000,NaN,NaN,NaN
37231,MAC000410,2012-12-18,NaN,NaN,NaN,1970-01-01 00:00:00.000000000,NaN,NaN,NaN
280220,MAC001257,2012-06-16,0.0400,0.040000,0.040,1970-01-01 00:00:00.000000001,NaN,0.040,0.040
...,...,...,...,...,...,...,...,...,...
97944,MAC000383,2014-01-08,0.0795,0.145417,1.206,1970-01-01 00:00:00.000000048,0.207633,6.980,0.004
97943,MAC000383,2014-01-07,0.0675,0.121979,0.664,1970-01-01 00:00:00.000000048,0.147144,5.855,0.002
97949,MAC000383,2014-01-13,0.0690,0.140563,0.874,1970-01-01 00:00:00.000000048,0.209172,6.747,0.000
292549,MAC000854,2012-10-23,0.1465,0.145729,0.439,1970-01-01 00:00:00.000000048,0.103772,6.995,0.026
292550,MAC000854,2012-10-24,0.1295,0.153042,NaN,NaT,NaN,NaN,NaN

In [17]:
data=a["energy_count"]
data

205939   1970-01-01 00:00:00.000000000
129012   1970-01-01 00:00:00.000000000
138461   1970-01-01 00:00:00.000000000
37231    1970-01-01 00:00:00.000000000
280220   1970-01-01 00:00:00.000000001
                      ...
97944    1970-01-01 00:00:00.000000048
97943    1970-01-01 00:00:00.000000048
97949    1970-01-01 00:00:00.000000048
292549   1970-01-01 00:00:00.000000048
292550                             NaT
Name: energy_count, Length: 292551, dtype: datetime64[ns]

In [11]:
from statsmodels.tsa.arima.model import ARIMA
model=ARIMA(data,order=(5,1,0))
model_fit=model.fit()
forecast = model_fit.forecast(steps=10)

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [19]:
print("Next 10 days energy max: ")
print("DAY 1:",forecast.iloc[0])
print("DAY 2:",forecast.iloc[1])
print("DAY 3:",forecast.iloc[2])
print("DAY 4:",forecast.iloc[3])
print("DAY 5:",forecast.iloc[4])
print("DAY 6:",forecast.iloc[5])
print("DAY 7:",forecast.iloc[6])
print("DAY 8:",forecast.iloc[7])
print("DAY 9:",forecast.iloc[8])
print("DAY 10:",forecast.iloc[9])

Next 10 days energy max:
DAY 1: 2.5075156311764912
DAY 2: 1.9171462674665962
DAY 3: 2.4682433929285255
DAY 4: 2.370137585496193
DAY 5: 2.792942475177486
DAY 6: 2.2560764981284254
DAY 7: 2.4259481175009703
DAY 8: 2.2708566667945997
DAY 9: 2.4696149818089994
DAY 10: 2.4078095105136215